binop_separator = "Front"
reorder_imports = true
reorder_modules = true
color = "Always"
combine_control_expr = false
comment_width = 100
control_brace_style = "ClosingNextLine"
edition = "2018"
enum_discrim_align_threshold = 20
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hard_tabs = true
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
indent_style = "Visual"
match_block_trailing_comma = true
max_width = 100
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
spaces_around_ranges = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
where_single_line = true
wrap_comments = true
